### ISSUE TITLE
qsfit_plot issue

### ISSUE THREAD

**Issue by JohanComparat** [gcalderone/qsfit#2]
Dear G. Calderone,
I successfully installed the code on a kubuntu machine with idl 8.5 and gnuplot 5.2.
The fit on the provided test file runs perfectly and I can write the results.
The execution of the plotting line to look at the results gives a strange error, pasted below. I am wondering if it is a known issue.
Thank you for your help,
Best regards, 
Johan

As you may see below the error involves tmp files, so the error is hard to track.
Executing the command with an output file does not solve the problem.

IDL> qsfit_plot, res, $filename='data/qsfit/spec-0752-52251-0323'
...
 Fit results 
#|FIT_STAT|TEST_STAT|TEST_DOF|TEST_PROB|MPFIT_STATUS|ELAPSED_TIME
0|  3914.3|   3914.3|    3248|        0|           0|      21.717
Total elapsed time: 21.717 seconds.
Log file: data/qsfit//spec-0752-52251-0323_QSFIT.log
Results saved in: data/qsfit//spec-0752-52251-0323_QSFIT.dat

IDL> qsfit_plot, res 
Using galaxy template: SWIRE_ELL5
  galaxy template flux density at 3650AA = 0.44222
  galaxy template flux density at 4400AA = 0.78098
  galaxy template flux density at 5100AA = 0.9311
  galaxy template flux density at 5500AA = 1
  galaxy template flux integrated in the range 3650AA +/- 340AA = 268.84
  galaxy template flux integrated in the range 4400AA +/- 490AA = 780.31
  galaxy template flux integrated in the range 5100AA +/- 50AA = 92.804
  galaxy template flux integrated in the range 5500AA +/- 445AA = 849.11
Interpolation of high order Balmer lines template...
Interpolation of Vestergaard and Wilkes (2001) UV iron template...
Interpolation of Veron-Cetty (2004) optical iron template...
% Program caused arithmetic error: Floating underflow
IDL> 
     reset session
                        ^
                         "/tmp/idl.gp.MbiffAhX", line 1: warning: expected optional axis name

                                                                                             reset session
                                                                                                                ^
                                                                                                                 "/tmp/idl.gp.MbiffAhX", line 1: ';' expected

                                 reset session
                                                    ^
                                                     "/tmp/idl.gp.TbllqnPR", line 1: warning: expected optional axis name

                                                                                                                         reset session
                ^
                 "/tmp/idl.gp.TbllqnPR", line 1: ';' expected

**Comment by gcalderone** [comment]
Hi Johan,
it's not easy to track down the issue since two files are involved in your case (idl.gp.TbllqnPR and idl.gp.MbiffAhX), while only one file at a time is used by qsfit.

Which gnuplot version are you using ?
Have you tried simple plot commands such as:
```
gplot, [1,2], [1,2], pl='w l'
```
?

If the above command fails, can you send me the temporary file producing the error ?

**Comment by gcalderone** [comment]
oops, gnuplot is vers. 5.2, which is OK.
Can you test the above command within IDL?

**Comment by JohanComparat** [comment]
Hi,

Indeed there is an issue when I execute this command :

gplot, [1,2], [1,2], pl='w l'
% Attempt to call undefined procedure: 'GPLOT'.
% Execution halted at: $MAIN$

**Comment by JohanComparat** [comment]
Maybe the compiler does not find the right gnuplot after all.
The machine has gnuplot 4.6 (in /usr/bin) and gnuplot 5.2 (alias to the gnuplot command in my bashrc)
So it is probably missing the link to the right gnuplot.

Is there something like ./configure in the code where I can pass this argument ?

**Comment by gcalderone** [comment]
Hi,
the error `% Attempt to call undefined procedure: 'GPLOT'` tells that you didn't compiled the qsfit code.
As described in USAGE you should go to the directory where you stored the QSFit files, start IDL,  and compile everything with the command `compile`.  Only after you can try the `gplot, [1,2], [1,2], pl='w l'` command.

To check whether you are using the appropriate gnuplot version you can use the following IDL command:
`SPAWN, "gnuplot -e 'print GPVAL_VERSION'"`

If the version is not 5.2 you should modify your login scripts to find the appropriate gnuplot executable. Remember that IDL always uses a bash shell...

**Comment by gcalderone** [comment]
If you want to hardcode a specific path to the gnuplot executable you should modify the `IDL/Glib/gnuplot/ggp.pro ` file, at line 176 (if you're using the qt terminal) or 180 (for any other terminal on linux)

**Comment by JohanComparat** [comment]
ok, I changed the pathes to redirect correctly to gnuplot. It now finds it :-) !

Now I have a bug with gnuplot_qt that cannot connect to the X server [see error below]. 
I am trying to solve this in parallel with the IT group here. Let's see ...

Thank you for your help,
Best wishes, Johan

IDL> qsfit_plot, res 
Using galaxy template: SWIRE_ELL5
  galaxy template flux density at 3650AA = 0.44222
  galaxy template flux density at 4400AA = 0.78098
  galaxy template flux density at 5100AA = 0.9311
  galaxy template flux density at 5500AA = 1
  galaxy template flux integrated in the range 3650AA +/- 340AA = 268.84
  galaxy template flux integrated in the range 4400AA +/- 490AA = 780.31
  galaxy template flux integrated in the range 5100AA +/- 50AA = 92.804
  galaxy template flux integrated in the range 5500AA +/- 445AA = 849.11
Interpolation of high order Balmer lines template...
Interpolation of Vestergaard and Wilkes (2001) UV iron template...
Interpolation of Veron-Cetty (2004) optical iron template...
% Program caused arithmetic error: Floating underflow
gnuplot_qt: cannot connect to X server 
IDL> gnuplot_qt: cannot connect to X server 

IDL> 
IDL> 
IDL> 
IDL> Could not connect to existing gnuplot_qt. Starting a new one.
                                                                  gnuplot_qt: cannot connect to X server 
                                                                                                         Could not connect to existing gnuplot_qt. Starting a new one.
               gnuplot_qt: cannot connect to X server 

IDL> 
IDL> 
     Warning: slow font initialization
                                      Warning: slow font initialization

**Comment by gcalderone** [comment]
Yes, I saw that error every now and then.  It is related to the way gnuplot and gnuplot_qt interact, but I don't know how to solve it.

To quickly solve the problem you can simply change the default gnuplot terminal in `IDL/Glib/gnuplot/ggp.pro`, line 107.  E.g.:
 ```
term = 'wxt'
```
or
 ```
term = 'x11'
```

**Comment by JohanComparat** [comment]
changing to 'wxt' made it work !
Thanks a lot,
Best regards
