### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by astro-fermi** [gcalderone/qsfit#3]
Hi,

I tried my first attempt to run qsfit on the spectrum file present inside data folder. I am using IDL 8.7 and have Gnuplot v5.0. I have a few doubts which I request you to clarify.

1- Do I need to compile every time I run the program?

2- Can I use qsfit to analyze SDSS-DR14 spectra?

3- I am able to compile without any error. Then I ran 
res = qsfit('data/spec-0752-52251-0323.fits', z=0.3806, ebv=0.06846)

The program ran for sometime, generated a few tables, and finally threw the following error
% Program caused arithmetic error: Floating underflow

Being new to IDL, I then tried to plot using 'qsfit_plot, res'. It then gave the following output and nothing happened.

Using galaxy template: SWIRE_ELL5
  galaxy template flux density at 3650AA = 0.44222
  galaxy template flux density at 4400AA = 0.78098
  galaxy template flux density at 5100AA = 0.9311
  galaxy template flux density at 5500AA = 1
  galaxy template flux integrated in the range 3650AA +/- 340AA = 268.84
  galaxy template flux integrated in the range 4400AA +/- 490AA = 780.31
  galaxy template flux integrated in the range 5100AA +/- 50AA = 92.804
  galaxy template flux integrated in the range 5500AA +/- 445AA = 849.11
Interpolation of high order Balmer lines template...
Interpolation of Vestergaard and Wilkes (2001) UV iron template...
Interpolation of Veron-Cetty (2004) optical iron template...
% Program caused arithmetic error: Floating underflow

**Comment by gcalderone** [comment]
Hi

> 1- Do I need to compile every time I run the program?

No, only the first time, right after you start the IDL session.

> 2- Can I use qsfit to analyze SDSS-DR14 spectra?

Yes, you can.

> 3- I am able to compile without any error. Then I ran
> res = qsfit('data/spec-0752-52251-0323.fits', z=0.3806, ebv=0.06846)
>
> The program ran for sometime, generated a few tables, and finally threw the following error
> % Program caused arithmetic error: Floating underflow

You can safely ignore all the Floating underflow errors, their purpose is simply to notify loss of numerical precision beyond the 6th or 7th significant digit.

> Being new to IDL, I then tried to plot using 'qsfit_plot, res'. It then gave the following output and nothing happened.

QSFit worked properly, but the plot were not shown because of a gnuplot problem.
QSFit uses the gnuplot qt terminal by default, hence you should check whether this terminal works appropriately using just gnuplot.  If you want to change the default terminal you can modify the line `term = 'qt'` in the `IDL/Glib/gnuplot/ggp.pro` file.

Alternatively you can run `qsfit_plot, res , filename='test', term='pdf'`.  Thi will generate two plot files in the current directory: `test.pdf` and `test_resid.pdf`.

**Comment by astro-fermi** [comment]
Thanks for the reply. I followed your both suggestions. First, I changed the default gnuplot terminal type from 'qt' to 'x11', which is the default gnuplot terminal in my MAC. Second, I also tried to run qsfit_plot command to save as pdf. Unfortunately, none of them show any plot and no pdf files are generated.

Is it possible to save the output (fitted model, residual, line parameters etc.) in the form of text files. This will enable me to plot them separately (e.g. using matplotlib). This will also help when I want to extract the output (e.g. line parameters in a tabular form) for a large number of spectral fitting.

Thanks.

**Comment by gcalderone** [comment]
> Unfortunately, none of them show any plot and no pdf files are generated.

Try to run the command `qsfit_plot, res , filename='test'` (without the `pdf` keyword).  This will create two files named `test.gp` and `test_resid.gp`.  Then open gnuplot and load them using (e.g.) `load 'test.gp'`.  This way you can investigate the problem without using IDL at all.   If needed, you can modify the gnuplot statements at the end of `test.gp`

**Comment by gcalderone** [comment]
You can save the output following this procedure:
```
res = qsfit(.....)
flat = qsfit_flatten_results(res)

; Check fields in the `flat` structure
HELP, flat

; Extract a substructure with the fields you're interested in, e.g.:
sel = gstru_sub(flat, keep=['NDATA', 'CONT1__LUM', 'CONT5100__SLOPE', 'CHISQ'])

; Open a file and print the results
OPENW, lun, 'Output.txt', /get_lun
gps, sel, lun=lun
FREE_LUN, lun
```

If you're analyzing several sources you can collect all the `flat` structures in an array, and print all the data at once with the last three statements.
