### ISSUE TITLE
report some bugs 

### ISSUE THREAD

**Issue by xychcz** [gcalderone/qsfit#5]
Many thanks for this wonderful tool!

I find some bugs in the new version 2.0, which are as follow:

1) In the "  ;; Calculate the sum of all QSFit components except "known" emission lines " part of Function qsfit_reduce, 
`  sum_wo_lines -= (out.expr.expr_broadlines - out.expr.expr_narrowlines)
`
should be
`  sum_wo_lines -= (out.expr.expr_broadlines + out.expr.expr_narrowlines)
`

2)  In Function qsfit_reduce_line, I suggest using the following code to deal with the associated line components:

`

    ;;If no association is made we just return the GFIT values
    IF (gn(assoc) EQ 1) THEN BEGIN
       line.ncomp    = 1
       line.lum      = gfit.comp.(assoc).par.norm.val
       line.lum_err  = gfit.comp.(assoc).par.norm.err

       IF (gfit.comp.(assoc).par.norm.expr EQ '') THEN BEGIN
          line.lum      = gfit.comp.(assoc).par.norm.val
          line.lum_err  = gfit.comp.(assoc).par.norm.err
       ENDIF $
       ELSE BEGIN
          line.lum     = gfit.comp.(assoc).par.norm.actual
          line.lum_err = gfit.comp.(assoc).par.norm.err / gfit.comp.(assoc).par.norm.val * gfit.comp.(assoc).par.norm.actual
       ENDELSE

       IF (gfit.comp.(assoc).par.v_off.expr EQ '') THEN BEGIN
          line.voff     = gfit.comp.(assoc).par.v_off.val
          line.voff_err = gfit.comp.(assoc).par.v_off.err
       ENDIF $
       ELSE BEGIN
          line.voff     = gfit.comp.(assoc).par.v_off.actual
          line.voff_err = gfit.comp.(assoc).par.v_off.err
       ENDELSE

       IF (gfit.comp.(assoc).par.fwhm.expr EQ '') THEN BEGIN
          line.fwhm     = gfit.comp.(assoc).par.fwhm.val
          line.fwhm_err = gfit.comp.(assoc).par.fwhm.err
       ENDIF $
       ELSE BEGIN
          line.fwhm     = gfit.comp.(assoc).par.fwhm.actual
          line.fwhm_err = gfit.comp.(assoc).par.fwhm.err / gfit.comp.(assoc).par.fwhm.val * gfit.comp.(assoc).par.fwhm.actual
       ENDELSE

    ENDIF $
    ELSE BEGIN

`

**Comment by gcalderone** [comment]
Hi,
thank you very much for your interest and for pointing out bug 1.  I slipped over it...

I'm not totally convinced about point 2.  Are you suggesting to handle parameter expressions on both line luminosity and v_off?
Unlike FWHM (through the `!QSFIT_OPT.bn_Fwhmtied` switch) there is no way to use such custom  expressions in QSFit, hence the user has to modify it anyway.

Can you provide a use case?

Thank you!!

**Comment by xychcz** [comment]
Hi gcalderone, 
thanks for the quick reply. For the second point, for example, in my case I need all of the luminosity (to a theoretical ratio), velocity shift and width of [OIII]4959 to be tied to those of [OIII]5007, the output will be wrong without the above setting. I guess other people could also require such features, although the code need to be modified further to set some switchs like !QSFIT_OPT.bn_Fwhmtied.

**Comment by gcalderone** [comment]
OK, implemented!
