### ISSUE TITLE
Error about SWIRE

### ISSUE THREAD

**Issue by ghost** [gcalderone/qsfit#6]
Thanks for your tools and it helps me a lot.
This is my second time to use this code. The code was running well on CentOS last time while have some trouble this time on macOS.
I run qsfit using IDL82 and Gnuplot v5.0 and got this error:

`IDL> in = qsfit_input('spec-1959-53440-0066.fits', type='SDSS_DR10', z=0.17806, ebv=0.0194)
IDL> res = qsfit(in)
********************************************************************************
QSFIT, ver. 2.0.0
  started: Tue Oct  9 22:30:34 2018

ID:
Spectral resolution (min, max): 68.999, 69.163 km s^-1
Fraction of "good" channels: 99.451%
  z=0.178059995174408
ebv=0.019400000572205

E(B-V) : 0.0194
Dereddening factors @ 1450, 3000, 5100 AA: 1.1639, 1.106, 1.0633

Cosmology:
#| H0|OMEGA_M|LAMBDA0
0| 70|    0.3|    0.7
Redshift: 0.17806
Lum. distance (Gpc): 0.86128

The line Lya has a coverage of       0.00000
The line NV_1241 has a coverage of       0.00000
The line OI_1306 has a coverage of       0.00000
The line CII_1335 has a coverage of       0.00000
The line SiIV_1400 has a coverage of       0.00000
The line CIV_1549 has a coverage of       0.00000
The line CIII_1909 has a coverage of       0.00000
The line CII has a coverage of       0.00000
The line MgII_2798 has a coverage of       0.00000
The line NeVI_3426 has a coverage of      0.910000
The line OII_3727 has a coverage of      0.910000
The line NeIII_3869 has a coverage of      0.910000
The line Hd has a coverage of      0.997500
The line Hg has a coverage of      0.997500
The line Hb has a coverage of      0.997500
The line OIII_4959 has a coverage of      0.910000
The line OIII_5007 has a coverage of      0.910000
The line HeI_5876 has a coverage of      0.997500
The line NII_6549 has a coverage of      0.980000
The line Ha has a coverage of      0.991667
The line NII_6583 has a coverage of      0.910000
The line SII_6716 has a coverage of      0.910000
The line SII_6731 has a coverage of      0.910000

Adding continuum component(s)...
   Continuum
   Galaxy
Using galaxy template: SWIRE_ELL5

===============================  GPRINT_ERROR  ===============================
Object reference type required in this context: SWIRE (COM_QSFIT_COMP_GALAXYTEMPLATE).

ERROR_STATE:
NAME            |BLOCK         | CODE|SYS_CODE|SYS_CODE_TYPE|SYS_MSG|MSG_PREFIX
IDL_M_REQOBJREF |IDL_MBLK_CORE | -762|    0, 0|             |       |%

IDL call stack:
ROUTINE                         |FILENAME                                                                                    | LINE
QSFIT_COMP_GALAXYTEMPLATE_CDATA |/Users/wenke/IDLWorkspace82/qsfit-master/IDL/qsfit/components/qsfit_comp_galaxytemplate.pro |  126
GFIT_COMPILE                    |/Users/wenke/IDLWorkspace82/qsfit-master/IDL/Glib/gfit/gfit_compile.pro                     |  125
QSFIT_COMPILE                   |/Users/wenke/IDLWorkspace82/qsfit-master/IDL/qsfit/qsfit.pro                                |  662
QSFIT_ADD_CONTINUUM             |/Users/wenke/IDLWorkspace82/qsfit-master/IDL/qsfit/qsfit.pro                                |  767
QSFIT_RUN                       |/Users/wenke/IDLWorkspace82/qsfit-master/IDL/qsfit/qsfit.pro                                | 2553
QSFIT                           |/Users/wenke/IDLWorkspace82/qsfit-master/IDL/qsfit/qsfit.pro                                | 3015
==============================================================================`

Even I tried release v1.2.4 and v1.2.0, this problem still occurred. I'm not quite sure if this is QSFit's problem or IDL's and I never meet error like this when I first use. 
Hoping for your reply and thanks a lot.

**Comment by gcalderone** [comment]
Hi.
version 2.0.0 is still experimental and although it significantly improves v1.2.4 you should use it with care until we publish the new catalog (hopefully in a few weeks).

Concerning the error, I'm not sure what the problem is.  I just tried with the spec-1959-53440-0066.fits spectrum  and it runs smoothly.

Could you please set `!glib.on_error=0` before starting the analysis?
This will stop the execution at the point where the error occurs, and you may issue the following commands to see what's going on:
```
help, swire  
help, swire.keys()
help, swire["ELL5"]
```

The correct output for the three commands above should be:
```
SWIRE (COM_QSFIT_COMP_GALAXYTEMPLATE) HASH  <ID=173  NELEMENTS=25>
<Expression>    LIST  <ID=231  NELEMENTS=25>
<Expression>    STRUCT    = -> <Anonymous> Array[1146]
```

If this is not the case could you please send me the output messages?

Thanks.

**Comment by ghost** [comment]
Thanks for your quick reply!
Following your suggestions, I use qsfit-1.2.4 to handle this spectrum and as I said before, this error still occurred.
After I compile this tool, I immediately run this spectrum and I got such error: 

```
IDL> res=qsfit('spec-1959-53440-0066.fits',z=0.17806417,ebv=0.0194)
********************************************************************************
QSFIT, ver. 1.2.4
  started at Wed Oct 10 08:28:35 2018

Input FILE   : spec-1959-53440-0066.fits   (format: SDSS_DR10)

Extra keywords:
EBV=0.019400000572205d
Z=0.178064167499542d

RA :  157.75
DEC:  31.049
Redshift: 0.17806
Spectral resolution (min, max): 68.999, 69.163 km s^-1
XX              DOUBLE    = Array[3640]
YY              DOUBLE    = Array[3640]
EE              DOUBLE    = Array[3640]
Z               DOUBLE    =       0.17806417
EBV             DOUBLE    =      0.019400001

E(B-V) : 0.0194
Dereddening factors @ 1450, 3000, 5100 AA: 1.1639, 1.106, 1.0633

Cosmology:
#| H0|OMEGA_M|LAMBDA0
0| 70|    0.3|    0.7
Redshift: 0.17806
Lum. distance (Gpc): 0.8613

Fraction of "good" channels: 99.451%

The line Lya has a coverage of       0.00000
The line NV_1241 has a coverage of       0.00000
The line OI_1306 has a coverage of       0.00000
The line CII_1335 has a coverage of       0.00000
The line SiIV_1400 has a coverage of       0.00000
The line CIV_1549 has a coverage of       0.00000
The line CIII_1909 has a coverage of       0.00000
The line MgII_2798 has a coverage of       0.00000
The line NeVI_3426 has a coverage of      0.910000
The line OII_3727 has a coverage of      0.910000
The line NeIII_3869 has a coverage of      0.910000
The line Hd has a coverage of      0.997500
The line Hg has a coverage of      0.997500
The line Hb has a coverage of      0.997500
The line OIII_4959 has a coverage of      0.910000
The line OIII_5007 has a coverage of      0.910000
The line HeI_5876 has a coverage of      0.997500
The line NII_6549 has a coverage of      0.980000
The line Ha has a coverage of      0.991667
The line NII_6583 has a coverage of      0.910000
The line SII_6716 has a coverage of      0.910000
The line SII_6731 has a coverage of      0.910000
Adding continuum component(s)...
   Continuum
   Galaxy

===============================  GPRINT_ERROR  ===============================
HASH::VALIDATE: Incorrect number of arguments.

ERROR_STATE:
NAME             |BLOCK         | CODE|SYS_CODE|SYS_CODE_TYPE|SYS_MSG|MSG_PREFIX
IDL_M_WRGNUMARGS |IDL_MBLK_CORE | -106|    0, 0|             |       |%

IDL call stack:
ROUTINE                        |FILENAME                                                                                   | LINE
GGALTEMPL_SWIRE                |/Users/wenke/IDLWorkspace82/qsfit-1.2.4/IDL/qsfit/components/ggaltempl_swire.pro           |   61
QSFIT_COMP_GALAXYTEMPLATE_INIT |/Users/wenke/IDLWorkspace82/qsfit-1.2.4/IDL/qsfit/components/qsfit_comp_galaxytemplate.pro |   58
GFIT_COMPONENT                 |/Users/wenke/IDLWorkspace82/qsfit-1.2.4/IDL/Glib/gfit/gfit_component.pro                   |   97
GFIT_ADD_COMP                  |/Users/wenke/IDLWorkspace82/qsfit-1.2.4/IDL/Glib/gfit/gfit_add_comp.pro                    |   66
QSFIT_ADD_CONTINUUM            |/Users/wenke/IDLWorkspace82/qsfit-1.2.4/IDL/qsfit/qsfit.pro                                |  753
QSFIT_RUN                      |/Users/wenke/IDLWorkspace82/qsfit-1.2.4/IDL/qsfit/qsfit.pro                                | 2496
QSFIT                          |/Users/wenke/IDLWorkspace82/qsfit-1.2.4/IDL/qsfit/qsfit.pro                                | 3009
==============================================================================

```
And after that, I tried this command one more time and the error changed.

```
Adding continuum component(s)...
   Continuum
   Galaxy
Using galaxy template: SWIRE_ELL5
% MPFIT: Error detected while calling mpfit_eval_model:
% MPFIT: Object reference type required in this context: SWIRE (COM_QSFIT_COMP_GALAXYTEMPLATE).
% MPFIT: Error condition detected. Returning to MAIN level.
Adding Balmer template...
Using galaxy template: SWIRE_ELL5
% MPFIT: Error detected while calling mpfit_eval_model:
% MPFIT: Object reference type required in this context: SWIRE (COM_QSFIT_COMP_GALAXYTEMPLATE).
% MPFIT: Error condition detected. Returning to MAIN level.
Using galaxy template: SWIRE_ELL5
% MPFIT: Error detected while calling mpfit_eval_model:
% MPFIT: Object reference type required in this context: SWIRE (COM_QSFIT_COMP_GALAXYTEMPLATE).
% MPFIT: Error condition detected. Returning to MAIN level.

MPFIT Status:      -18
Routine mpfit reported an error:
Error detected while calling mpfit_eval_model: Object reference type required in this context: SWIRE (COM_QSFIT_COMP_GALAXYTEMPLATE).

Parameter values in last iteration:
             NaN

===============================  GPRINT_ERROR  ===============================
GFIT_RUN: Routine mpfit reported an error: Error detected while calling mpfit_eval_model: Object reference type required in this context: SWIRE
             (COM_QSFIT_COMP_GALAXYTEMPLATE).

ERROR_STATE:
NAME           |BLOCK         |CODE|SYS_CODE|SYS_CODE_TYPE|SYS_MSG|MSG_PREFIX
IDL_M_USER_ERR |IDL_MBLK_CORE |  -5|    0, 0|             |       |%

IDL call stack:
ROUTINE   |FILENAME                                                           | LINE
GFIT_RUN  |/Users/wenke/IDLWorkspace82/qsfit-1.2.4/IDL/Glib/gfit/gfit_run.pro |   76
QSFIT_RUN |/Users/wenke/IDLWorkspace82/qsfit-1.2.4/IDL/qsfit/qsfit.pro        | 2498
QSFIT     |/Users/wenke/IDLWorkspace82/qsfit-1.2.4/IDL/qsfit/qsfit.pro        | 3009
==============================================================================
```

And that seems to be the final error and will not change if I try again. Then I set `!glib.on_error=0` and those three command returned me following info:

```
IDL> help, swire
SWIRE           UNDEFINED = <Undefined>
IDL> help, swire.keys()
% Object reference type required in this context: SWIRE.
% Execution halted at: GFIT_RUN           76 /Users/wenke/IDLWorkspace82/qsfit-1.2.4/IDL/Glib/gfit/gfit_run.pro
%                      QSFIT_RUN        2498 /Users/wenke/IDLWorkspace82/qsfit-1.2.4/IDL/qsfit/qsfit.pro
%                      QSFIT            3009 /Users/wenke/IDLWorkspace82/qsfit-1.2.4/IDL/qsfit/qsfit.pro
%                      $MAIN$
IDL> help, swire["ELL5"]
% Variable is undefined: SWIRE.
% Execution halted at: GFIT_RUN           76 /Users/wenke/IDLWorkspace82/qsfit-1.2.4/IDL/Glib/gfit/gfit_run.pro
%                      QSFIT_RUN        2498 /Users/wenke/IDLWorkspace82/qsfit-1.2.4/IDL/qsfit/qsfit.pro
%                      QSFIT            3009 /Users/wenke/IDLWorkspace82/qsfit-1.2.4/IDL/qsfit/qsfit.pro
%                      $MAIN$
```

Does it looks like some kind of function named 'SWIRE' is missing or broken?
This problem is not for all spectrums I tried to fit. For some specific spectrums, this code run quite well and returned me right fitting result, but this problem still bothered me.
By the way, the version of my Gnuplot is 5.2. Sorry for misremembering.

**Comment by gcalderone** [comment]
Hi,
the order of the operations should be as follows:
- change to the directory where `spec-1959-53440-0066.fits` is;
- start IDL
- type:
```
!glib.on_error=0 before starting the analysis?
res=qsfit('spec-1959-53440-0066.fits',z=0.17806417,ebv=0.0194)
```
- Then the execution will stop at the level where the error occurred.  Now you can type
```
help, swire  
help, swire.keys()
help, swire["ELL5"]
```
- report the output here.

Please ensure that you are not mixing QSFit code from different versions.

Thank you.

**Comment by ghost** [comment]
Sorry for telling you that with the help of my classmates, I find that somehow the HASH function in my IDL doesn't work so that your code meet some trouble. Many thanks!
